### ISSUE TITLE
`PKG-INFO` in sdist is missing `License-File`

### ISSUE THREAD

**Issue by mtelka** [pasteorg/paste#101]
The sdist package contains license in `docs/license.txt`, but the package metadata does not point there.  It would be great if either the `PKG-INFO` contains something like (see PEP 639):
```
License-File: docs/license.txt
```
or the license is moved to `LICENSE` file.

Thank you.

**Comment by mtelka** [comment]
I think [this](https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script) contains some hints how to do that.

**Comment by cdent** [comment]
Fixed in #100
