### ISSUE TITLE
Question. What's the licence of paste?

### ISSUE THREAD

**Issue by avgvsto** [pasteorg/paste#54]
I would like to know what the licence of paste is 🙂. Thanks!

**Comment by cdent** [comment]
MIT, see https://pypi.org/project/Paste/ or https://github.com/cdent/paste/blob/7b6cfdfe132a5f5e6631a5fe8d3492538c1d0d78/setup.py#L33

Unless you are already using Paste for something, I would not recommend starting something new with it. It's very out of date and currently only maintained here to keep existing projects that are stuck on it alive.

**Comment by cdent** [comment]
#100 makes the license more clear
